export class JL {
  getJudgmentList(options) {
    const mainArray = [
      [
        { title: '戦闘でよく使用される判定' },
        { title: '先制判定', skills: ['機先'] },
        { title: '命中判定', ability: ['技量', '集中'], classes: ['戦士', '武道家', '斥候', '野伏'], skills: ['武器：〇〇', '超命中'] },
        { title: '回避判定', ability: ['技量', '反射'], classes: ['戦士', '武道家', '斥候'], skills: ['体術', '受け流し', '超反射'] },
        { title: '盾受け判定', ability: ['技量', '反射'], classes: ['戦士', '斥候'], skills: ['盾'] },
        { title: '呪文行使判定', ability: ['知力', '集中'], classes: ['魔術師', '死人占い師'], skills: ['呪文熟達：〇〇'] },
        { title: '呪文行使判定', ability: ['魂魄', '集中'], classes: ['神官', '竜司祭', '精霊使い'], skills: ['呪文熟達：〇〇'] },
        { title: '呪文維持判定', ability: ['知力', '集中'], classes: ['魔術師', '死人占い師'], skills: ['呪文熟達：〇〇'] },
        { title: '呪文維持判定', ability: ['魂魄', '集中'], classes: ['神官', '竜司祭', '精霊使い'], skills: ['呪文熟達：〇〇'] },
        { title: '呪文抵抗判定', ability: ['魂魄', '反射'], classes: ['冒険者'], skills: ['呪文抵抗'] },
        { title: '挑発判定', ability: ['魂魄', '集中'], classes: ['戦士', '武道家'], skills: ['挑発'] },
        { title: '移動妨害判定', ability: ['体力', '反射'], classes: ['戦士'], skills: ['鉄壁'] },
        { title: '移動妨害への対抗判定', ability: ['体力', '集中'], classes: ['戦士', '武道家', '斥候'], skills: ['すり抜け'] },
        { title: '移動妨害への対抗判定', ability: ['技量', '集中'], classes: ['戦士', '武道家', '斥候'], skills: ['すり抜け'] },
      ],
      [
        { title: '抵抗系判定', },
        { title: '体力抵抗判定', ability: ['体力', '反射'], classes: ['冒険者'], skills: ['免疫強化'] },
        { title: '魂魄抵抗判定', ability: ['魂魄', '反射'], classes: ['冒険者', '竜司祭'], skills: ['冷静沈着'] },
        { title: '知力抵抗判定', ability: ['知力', '反射'], classes: ['冒険者', '竜司祭'], skills: ['冷静沈着'] },
        { title: '呪文抵抗判定', ability: ['魂魄', '反射'], classes: ['冒険者'], skills: ['呪文抵抗'] },
      ],
      [
        { title: '筋力系判定', },
        { title: '怪力判定', ability: ['体力', '集中'], classes: ['戦士', '武道家'], skills: ['過重行動', '超怪力'] },
        { title: '脱出判定', ability: ['体力', '集中'], classes: ['戦士', '武道家'], skills: ['過重行動', '超怪力'] },
        { title: '登攀判定（筋力系）', ability: ['体力', '持久'], classes: ['戦士', '武道家'], skills: ['過重行動', '超怪力'] },
      ],
      [
        { title: '運動系判定', },
        { title: '水泳判定', ability: ['技量', '集中'], classes: ['冒険者'], skills: ['体術', '超反射'] },
        { title: '登攀判定（運動系）', ability: ['技量', '持久'], classes: ['斥候', '野伏'], skills: ['体術', '超反射'] },
        { title: '軽業判定', ability: ['技量', '集中'], classes: ['武道家', '斥候', '野伏'], skills: ['体術', '超反射'] },
        { title: '跳躍判定', ability: ['技量', '集中'], classes: ['武道家', '斥候', '野伏'], skills: ['体術', '超反射'] },
        { title: '回避判定', ability: ['技量', '反射'], classes: ['戦士', '武道家', '斥候'], skills: ['体術', '受け流し', '超反射'] },
      ],
      [
        { title: '操作系判定', },
        { title: '応急手当判定', ability: ['技量', '集中'], classes: ['野伏', '神官', '竜司祭', '死人占い師'], skills: ['応急手当', '生体知識', '介護'] },
        { title: '手仕事判定', ability: ['技量', '集中'], classes: ['斥候', '野伏'], skills: ['手仕事'] },
        { title: '命中判定', ability: ['技量', '集中'], classes: ['戦士', '武道家', '斥候'], skills: ['武器：〇〇'] },
        { title: '盾受け判定', ability: ['技量', '反射'], classes: ['戦士', '斥候'], skills: ['盾'] },
      ],
      [
        { title: '隠密系判定', },
        { title: '隠密判定', ability: ['技量', '集中'], classes: ['斥候', '野伏'], skills: ['隠密', '影渡り', '霧化'] },
        { title: '手仕事判定', ability: ['技量', '集中'], classes: ['斥候', '野伏'], skills: ['手仕事'] },
      ],
      [
        { title: '知識系判定', },
        { title: '怪物知識判定', ability: ['知力', '集中'], classes: ['魔術師', '神官', '竜司祭', '精霊使い', '死人占い師'], skills: ['怪物知識'] },
        { title: '博識判定', ability: ['知力', '集中'], classes: ['魔術師'], skills: ['博識'] },
        { title: '魔術知識判定', ability: ['知力', '集中'], classes: ['魔術師'], },
      ],
      [
        { title: '感知系判定', },
        { title: '観察判定', ability: ['知力', '集中'], classes: ['斥候', '野伏'], skills: ['観察', '超感覚'] },
        { title: '第六感判定', ability: ['知力', '反射'], classes: ['斥候', '野伏', '精霊使い'], skills: ['第六感', '超感覚'] },
      ],
      [
        { title: '移動系判定', },
        { title: '移動妨害判定', ability: ['体力', '反射'], classes: ['戦士'], skills: ['鉄壁', '超反射'] },
        { title: '移動妨害への対抗判定', ability: ['体力', '集中'], classes: ['戦士', '武道家', '斥候'], skills: ['超反射'] },
        { title: '移動妨害への対抗判定', ability: ['技量', '集中'], classes: ['戦士', '武道家', '斥候'], skills: ['超反射'] },
        { title: '長距離移動判定', ability: ['体力', '持久'], classes: ['冒険者'], skills: ['長距離移動'] },
      ]
    ]
    const addArray = [
      { title: '技能一覧にて掲載されている判定', },
      { title: '不意打ち判定', ability: ['技量', '集中'], classes: ['斥候', '野伏'], skills: ['機先', '隠密', '影渡り', '霧化'] },
      { title: '戦術移動判定', ability: ['知力', '集中'], skills: ['戦術移動'] },
      { title: '祈念判定', skills: ['幸運'] },
      { title: '手仕事判定（操作系判定）', ability: ['技量', 'GM'], classes: ['斥候'], skills: ['手仕事'] },
      { title: '統率判定', ability: ['魂魄', 'GM'], skills: ['統率'] },
      { title: '祈祷判定', ability: ['魂魄', 'GM'], classes: ['神官', '竜司祭', '死人占い師'], skills: ['祈祷'] },
      { title: '瞑想判定', ability: ['知力', 'GM'], classes: ['魔術師', '精霊使い', '死人占い師'], skills: ['瞑想'] },
      { title: '鑑定判定', ability: ['知力', 'GM'], skills: ['鑑定'] },
      { title: '交渉判定：説得（交渉系判定）', ability: ['知力', 'GM'], skills: ['交渉：説得'] },
      { title: '交渉判定：誘惑（交渉系判定）', ability: ['魂魄', 'GM'], skills: ['交渉：誘惑'] },
      { title: '交渉判定：脅迫（交渉系判定）', ability: ['体力', 'GM'], skills: ['交渉：脅迫'] },
      { title: '神学判定（知識系判定）', ability: ['知力', 'GM'], classes: ['神官', '竜司祭'], skills: ['神学'] },
      { title: '生存術知識判定（知識判定）', ability: ['知力', 'GM'], classes: ['野伏'], skills: ['生存術'] },
      { title: '生存術技術判定（操作判定）', ability: ['技量', 'GM'], classes: ['野伏'], skills: ['生存術'] },
      { title: '直感判定（感知系判定）', ability: ['魂魄', 'GM'], skills: ['先入観なし', '超感覚'] },
      { title: '動揺を鎮める判定', ability: ['魂魄', 'GM'], classes: ['冒険者', '竜司祭'], skills: ['冷静沈着'] },
      { title: '動揺を鎮める判定', ability: ['知力', 'GM'], classes: ['冒険者', '竜司祭'], skills: ['冷静沈着'] },
      { title: '博識判定（知識系判定）', ability: ['知力', 'GM'], classes: ['魔術師'], skills: ['博識'] },
      { title: '犯罪知識判定（知識系判定）', ability: ['知力', 'GM'], classes: ['斥候'], skills: ['犯罪知識'] },
      { title: '文献調査判定（知識系判定）', ability: ['知力', 'GM'], skills: ['文献調査'] },
      { title: '礼儀作法判定（交渉系判定）', ability: ['魂魄', 'GM'], classes: ['死人占い師'], skills: ['礼儀作法'] },
      { title: '労働判定', ability: ['体力', 'GM'], skills: ['労働'] },
      { title: '労働判定', ability: ['知力', 'GM'], skills: ['労働'] },
      { title: '生産業知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['生産業：〇〇'] },
      //{ title: '農業知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['生産業：農業'] },
      //{ title: '漁業知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['生産業：漁業'] },
      //{ title: '林業知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['生産業：林業'] },
      //{ title: '採掘知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['生産業：採掘'] },
      { title: '生産業技術判定（操作系判定）', ability: ['技量', 'GM'], skills: ['生産業：〇〇'] },
      //{ title: '農業技術判定（操作系判定）', ability: ['技量', 'GM'], skills: ['生産業：農業'] },
      //{ title: '漁業技術判定（操作系判定）', ability: ['技量', 'GM'], skills: ['生産業：漁業'] },
      //{ title: '林業技術判定（操作系判定）', ability: ['技量', 'GM'], skills: ['生産業：林業'] },
      //{ title: '採掘技術判定（操作系判定）', ability: ['技量', 'GM'], skills: ['生産業：採掘'] },
      //{ title: '職人製作判定（操作系判定）', ability: ['技量', 'GM'], skills: ['職人：〇〇'] },
      //{ title: '職人知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['職人：〇〇'] },
      { title: '芸能実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：〇〇'] },
      //{ title: '歌唱実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：歌唱'] },
      //{ title: '演奏実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：演奏'] },
      //{ title: '舞踊実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：舞踊'] },
      //{ title: '大道芸実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：大道芸'] },
      //{ title: '演劇実演判定', ability: ['魂魄', 'GM'], skills: ['芸能：演劇'] },
      { title: '芸能知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：〇〇'] },
      //{ title: '歌唱知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：歌唱'] },
      //{ title: '演奏知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：演奏'] },
      //{ title: '舞踊知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：舞踊'] },
      //{ title: '大道芸知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：大道芸'] },
      //{ title: '演劇知識判定（知識系判定）', ability: ['知力', 'GM'], skills: ['芸能：演劇'] },
      { title: '工作判定（操作系判定）', ability: ['技量', 'GM'], skills: ['工作'] },
      { title: '乗馬判定（操作系判定）', ability: ['技量', 'GM'], skills: ['乗馬'] },
      { title: '調理知識判定（知識判定）', ability: ['知力', 'GM'], skills: ['調理'] },
      { title: '調理技術判定（操作判定）', ability: ['技量', 'GM'], },
    ]
    const supArray = [
      { title: 'サプリメントにて追加された判定', },
      { title: '吸血判定', ability: ['魂魄', '集中'], classes: ['冒険者'], skills: ['吸血'] },
      { title: '吸血鬼感知判定（感知系判定）', ability: ['知力', 'GM'], classes: ['冒険者'], skills: ['吸血鬼感知', '超感覚'] },
      { title: '邪悪感知判定（感知系判定）', ability: ['知力', 'GM'], classes: ['冒険者'], skills: ['邪悪感知', '超感覚'] },
      { title: '魔眼判定', ability: ['魂魄', '集中'], classes: ['冒険者'], skills: ['魔眼：〇〇'] },
      { title: '修理判定', ability: ['技量', '集中'], skills: ['職人：〇〇'] },
      { title: '応急修理判定', ability: ['技量', '集中'], skills: ['工作'] },
      { title: '鎮静化のための騎乗判定', ability: ['技量', '集中'], skills: ['乗馬'] },
      //{ title: '魔法知識判定　❓不明（魔術知識判定？）', skills: ['生体知識'] },
      { title: '迷宮知識判定', ability: ['知力', '集中'], classes: ['冒険者'], skills: ['迷宮知識'] },
      { title: '看護判定', ability: ['知力', 'GM'], skills: ['介護'] },
      { title: '拷問判定', ability: ['魂魄', 'GM'], classes: ['斥候'], skills: ['拷問'] },
      { title: '地図製作判定', ability: ['知力', 'GM'], classes: ['斥候', '野伏'], skills: ['地図製作'] },
      { title: '赦しの秘跡判定', ability: ['知力', 'GM'], classes: ['神官', '竜司祭'], skills: ['赦しの秘跡'] },
    ]
    // 設定ごとに生成するコマンドを変える
    let commandsArray = [...mainArray]
    if (options.add) commandsArray.push(addArray)
    if (options.sup) commandsArray.push(supArray)
    
    return commandsArray
  }
  getAllClassesArray() {
    const array = ['戦士', '武道家', '斥候', '野伏', '魔術師', '神官', '竜司祭', '精霊使い', '死人占い師']
    return array
  }
  getAllSkillsArray() {
    const array = [
      'すり抜け',
      '隠密',
      '影渡り',
      '応急手当',
      '過重行動',
      '介護',
      '怪物知識',
      '観察',
      '鑑定',
      '機先',
      '祈祷',
      '吸血',
      '吸血鬼感知',
      '芸能：〇〇',
      '芸能：演劇',
      '芸能：演奏',
      '芸能：歌唱',
      '芸能：大道芸',
      '芸能：舞踊',
      '交渉：脅迫',
      '交渉：説得',
      '交渉：誘惑',
      '工作',
      '幸運',
      '拷問',
      '赦しの秘跡',
      '邪悪感知',
      '手仕事',
      '受け流し',
      '呪文熟達：〇〇',
      '呪文抵抗',
      '盾',
      '乗馬',
      '職人：〇〇',
      '神学',
      '生産業：〇〇',
      '生産業：漁業',
      '生産業：採掘',
      '生産業：農業',
      '生産業：林業',
      '生存術',
      '生体知識',
      '先入観なし',
      '戦術移動',
      '体術',
      '第六感',
      '地図製作',
      '挑発',
      '調理',
      '超怪力',
      '超感覚',
      '超反射',
      '超命中',
      '長距離移動',
      '鉄壁',
      '統率',
      '博識',
      '犯罪知識',
      '武器：〇〇',
      '文献調査',
      '魔眼：〇〇',
      '霧化',
      '迷宮知識',
      '免疫強化',
      '冷静沈着',
      '礼儀作法',
      '労働',
      '瞑想',
    ]
    return array
  }
}